SixthProject/FirstApp/urls.py
from django.urls import path
from . import views
# we can also write this as from .views import TahnkYouView,ContactFormView,...TeacherDeleteView

app_name='FirstApp'

urlpatterns = [
    path('',views.home_view,name='home'),
    path('thankyou/',views.ThankYouView.as_view(),name='thankyou'),
    path('contact/',views.ContactFormView.as_view(),name='contact'),
    path('create_teacher/',views.TeacherCreateView.as_view(),name='create_teacher'),
    path('list_teacher/',views.TeacherListView.as_view(),name='list_teacher'),
    path('teacher_detail/<int:pk>',views.TeacherDetailView.as_view(),name='detail_teacher'),
    path('teacher_update/<int:pk>',views.TeacherUpdateView.as_view(),name='teacher_update'),
    path('teacher_delete/<int:pk>',views.TeacherDeleteView.as_view(),name='teacher_delete'),

]

SixthProject/SixthProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('FirstApp/',include('FirstApp.urls'))
]

SixthProject/FirstApp/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    subject  = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.first_name} {self.last_name} teaches {self.subject}"

SixthProject/FirstApp/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)
    

SixthProject/FirstApp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,FormView,CreateView,ListView,DetailView,UpdateView, DeleteView
from django.urls import reverse_lazy
from . import forms
from . import models

# Create your views here.


#http://127.0.0.1:8080/FirstApp
# this is the function based view
def home_view(request):
    return render(request,'FirstApp/home.html')


#http://127.0.0.1:8080/FirstApp/thankyou

# this is the class based view
class ThankYouView(TemplateView):
    # connecting to the html file 
    template_name = 'FirstApp/thankyou.html'
    #now we have to connect this to urls.py
    #and urls.py needs a function 
    # ThankYouView.as_view() in urls.py 


# this is form view
class ContactFormView(FormView):
    form_class = forms.ContactForm
        # connecting to the html file 
    template_name = 'FirstApp/contact.html'

    # success URL? 
    ''' u can directly use as below or u can also use reverse lazy
    success_url = "/FirstApp/thankyou/"'''
    success_url = reverse_lazy("FirstApp:thankyou")

    #what to do with form
    # this is with request==POST
    def form_valid(self,form):
        print(form.cleaned_data)
        # https://docs.djangoproject.com/en/4.1/topics/class-based-views/generic-editing/
        # below line is with inheritance we are calling FormView.form_valid()
        # The default implementation for form_valid() simply redirects to the success_url.
        # AM not sure if this really has a validation i think we have to do the validation here
        # 
        return super().form_valid(form)
        '''def form_valid(self, form):
        """If the form is valid, redirect to the supplied URL."""
        return HttpResponseRedirect(self.get_success_url())'''

#http://127.0.0.1:8080/FirstApp/

class TeacherCreateView(CreateView):
    model = models.Teacher  # it is not Teacher()
    # as we have given the model it automatically looks for the template Teacher_form.hmtl
    # fields to be displayed on the create form
    fields = "__all__" # or u can give  a list []
    # it automatically calls .save() on the model on click of submit
    success_url = reverse_lazy("FirstApp:thankyou")


#http://127.0.0.1:8080/FirstApp/
class TeacherListView(ListView):
    model = models.Teacher  # it is not Teacher()

    context_object_name ="teacher_list"
    # if context_object name isnot  specified 
    # {% for teacher in object_list   %}     
    #    by default it is object_list
    #but if u specify any context_object_name then use that here 
    #like context_object_name ="teacher_list"-->
    # #<ul>{% for teacher in  teacher_list %}
    
    
    # u need not specify the queryset
    # it is by default queryset = Teacher.objects.all()
    # but u can override
    queryset = models.Teacher.objects.order_by('first_name')
  
# goto http://127.0.0.1:8080/FirstApp/
# add some records and goto list and then click on each teacher link to goto detailed view
class TeacherDetailView(DetailView):
    model = models.Teacher  # it is not Teacher()
    # for a specific primary key of a teacher
    # pk --> {{teacher}}


class TeacherUpdateView(UpdateView):
    # it share model_form.html that create view uses ---- Primary key 
    model = models.Teacher  # it is not Teacher()
    fields = "__all__" # or u can have a list of fields for update
    success_url = reverse_lazy("FirstApp:thankyou")

class TeacherDeleteView(DeleteView):
    # form -- single confirm delete button
    # it looks for model_confirm _delete.html
    model = models.Teacher
    success_url = reverse_lazy("FirstApp:list_teacher")

SixthProject/FirstApp/templates/FirstApp/contact.html
<h1> this is classs based views form view template</h1>

<form method='POST'>
{% csrf_token %}
{{form.as_p}}
<input type="submit">
</form>

SixthProject/FirstApp/templates/FirstApp/home.html
<h1> Welcome Home</h1b>
    <ul>
        <li><a href="{% url "FirstApp:thankyou" %}">class based view Template view</li>
        <li><a href="{% url "FirstApp:contact" %}">class based views -  Form view</li>

            <li><a href="{% url "FirstApp:create_teacher" %}">class based views -  create teacher view</li>
                <li><a href="{% url "FirstApp:list_teacher" %}">class based views -  list teacher view</li>

    </ul>

SixthProject/FirstApp/templates/FirstApp/teacher_confirm_delete.html
<h1> Are you sure u want to delete this teacher</h1>
{{teacher}}
<form method = 'POST'>
    {% csrf_token %}
    <input type="submit" value = "Confirm Delete1">



</form>

SixthProject/FirstApp/templates/FirstApp/teacher_detail.html
<h1> detail view of Teachers  </h1>
 {{teacher}}

SixthProject/FirstApp/templates/FirstApp/teacher_form.html
<h1> Teacher form </h1>
<form method = 'POST'>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">



</form>

SixthProject/FirstApp/templates/FirstApp/teacher_list.html
<h1> list of Teachers  </h1>
 
<!--{% for teacher in object_list   %}     {% endfor %}
    by default it is object_list
but if u specify any context_object_name then use that here 
like context_object_name ="teacher_list"-->

<ul>{% for teacher in  teacher_list %}
    <li><a href="/FirstApp/teacher_detail/{{teacher.id}}" >{{teacher.first_name}} {{teacher.last_name}}</a>
        <ul><li>
        <a href="/FirstApp/teacher_update/{{teacher.id}}" >Update info.</a>
        </li>
        <li>
            <a href="/FirstApp/teacher_delete/{{teacher.id}}" >Delete</a>
        </li>
    </ul>

    </li>
    
    {% endfor %}
</ul>


</form>

SixthProject/FirstApp/templates/FirstApp/thankyou.html
<h1> this is classs based views template view</h1>